# Generated by Django 5.0.7 on 2024-08-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customer_user'),
        ('dashboard', '0001_initial'),
        ('sales', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='recent_activities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportticket'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='sales_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='total_customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
